const objectId = Joi => Joi.string().hex().length(24);
const Joi = require('joi');

const supplier = Joi.object({ supplierCode: Joi.string().trim().max(30).required(), name: Joi.string().trim().max(200).required(), taxId: Joi.string().trim().max(50).allow(''), currency: Joi.string().length(3).uppercase().default('USD'), paymentTermsDays: Joi.number().integer().min(0).default(30), active: Joi.boolean().default(true) });
const poLine = Joi.object({ lineNumber: Joi.number().integer().min(1).required(), sku: Joi.string().trim().max(100).required(), description: Joi.string().trim().max(500).allow(''), orderedQuantity: Joi.number().positive().required(), unitPrice: Joi.number().min(0).required(), taxRate: Joi.number().min(0).max(100).default(0) });
const purchaseOrder = Joi.object({ poNumber: Joi.string().trim().max(50).required(), supplier: objectId(Joi).required(), currency: Joi.string().length(3).uppercase().required(), issueDate: Joi.date().iso().required(), lines: Joi.array().items(poLine).min(1).required(), status: Joi.string().valid('OPEN', 'PARTIALLY_RECEIVED', 'FULLY_RECEIVED', 'CLOSED', 'CANCELLED').default('OPEN') });
const receiptLine = Joi.object({ poLineNumber: Joi.number().integer().min(1).required(), sku: Joi.string().trim().max(100).required(), receivedQuantity: Joi.number().min(0).required(), receivedDate: Joi.date().iso().required() });
const goodsReceipt = Joi.object({ receiptNumber: Joi.string().trim().max(50).required(), purchaseOrder: objectId(Joi).required(), receivedBy: Joi.string().trim().max(200).allow(''), lines: Joi.array().items(receiptLine).min(1).required(), status: Joi.string().valid('POSTED', 'REVERSED').default('POSTED') });
const invoiceLine = Joi.object({ poLineNumber: Joi.number().integer().min(1).required(), sku: Joi.string().trim().max(100).required(), description: Joi.string().trim().max(500).allow(''), invoicedQuantity: Joi.number().positive().required(), unitPrice: Joi.number().min(0).required(), taxRate: Joi.number().min(0).max(100).default(0) });
const invoice = Joi.object({ invoiceNumber: Joi.string().trim().max(50).required(), supplier: objectId(Joi).required(), purchaseOrder: objectId(Joi).required(), invoiceDate: Joi.date().iso().required(), dueDate: Joi.date().iso().allow(null), currency: Joi.string().length(3).uppercase().required(), lines: Joi.array().items(invoiceLine).min(1).required(), subtotal: Joi.number().min(0).required(), taxTotal: Joi.number().min(0).default(0), total: Joi.number().min(0).required(), status: Joi.string().valid('RECEIVED', 'MATCHED', 'MISMATCHED', 'APPROVED', 'REJECTED', 'PAID').default('RECEIVED'), reviewNote: Joi.string().trim().max(1000).allow('') });

module.exports = { supplier, purchaseOrder, goodsReceipt, invoice };
